version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAG_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    GOOGLE_APPLICATION_CREDENTIALS: /keys/clarifai-sa-key.json
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/requirements.txt:/requirements.txt
    - ./src:/opt/airflow/src
    - ./secrets/clef.json:/keys/clarifai-sa-key.json:ro
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-init:
    <<: *airflow-common
    entrypoint: >
      bash -c "pip install -r /requirements.txt && airflow db migrate && airflow users create \
      --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email admin@example.com"

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    <<: *airflow-common
    command: scheduler

  worker:
    <<: *airflow-common
    command: celery worker

  triggerer:
    <<: *airflow-common
    command: triggerer

volumes:
  postgres-db-volume: